#################################################################################
# Copyright (c) 2014-2020 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.
#
################################################################################

version: "3.7"

services:
  debug:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    working_dir: "/debug"
    volumes:
      - logging-oneui-server:/debug/oneui-server
    networks:
      - fusion

# This service creates the One UI Server component to manage both zones.
#
# Note: this component can be run in either zone, so one is chosen arbitrarily

  # Fusion OneUI Server
  fusion-oneui-server:
    image: wandisco/fusion-oneui:3.18.0
    restart: unless-stopped
    networks:
      - fusion
    ports:
      - 8081:8081
    environment:
      - FUSION_SERVER_HOSTNAMES=http://fusion-server-sandbox-hdp:8082,http://fusion-server-adls2:8582
    env_file:
      - "common.env"
    volumes:
      - logging-oneui-server:/var/log/fusion/
      - fusion-oneui-h2db:/h2db
      - fusion-sandbox-hdp-restart:/etc/wandisco/fusion/server/sandbox-hdp
      - fusion-adls2-restart:/etc/wandisco/fusion/server/adls2
      - fusion-sandbox-hdp-etc-wandisco:/fusionConfig/sandbox-hdp
      - fusion-adls2-etc-wandisco:/fusionConfig/adls2
      - fusion-license:/etc/wandisco/license

volumes:
  # Named logging volume
  logging-oneui-server:

  # h2db database for UI Server
  fusion-oneui-h2db:

  # Used for restarting fusion-server, fusion-ui-server and ihc servers
  fusion-sandbox-hdp-restart:
  fusion-adls2-restart:
  fusion-sandbox-hdp-etc-wandisco:
  fusion-adls2-etc-wandisco:

  fusion-license:
