version: '3.7'

services:
  freeipa:
    container_name: freeipa
    image: freeipa/freeipa-server:centos-9-stream-4.12.2
    restart: unless-stopped
    hostname: <hostname>
    environment:
      NO_NTP: 1
      IPA_SERVER_HOSTNAME: <hostname>
      TZ: "Europe/Moscow"
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    volumes:
      - freeipa_data:/data
      - /etc/localtime:/etc/localtime:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    command:
      - ipa-server-install
      - --domain=<realm>
      - --realm=<realm>
      - --http-pin=
      - --dirsrv-pin=e
      - --ds-password=
      - --admin-password=
      - --no-host-dns
      - --setup-dns
      - --unattended
    ports:
      - "53:53"
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"
    logging:
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  freeipa_data:
